# Last stable Python version
FROM python:3.10-slim-buster

# Create application directory and move there
WORKDIR /app

# Copy requirements file from the host to the container
COPY requirements.txt ./

# Install these requirements
RUN pip install --no-cache-dir --prefer-binary -r requirements.txt
RUN pip install waitress

# Copy the rest of the application files
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the API server
CMD ["waitress-serve", "--port=8080", "app:app"]
